#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
import helpers

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets username")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze word
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    print(tweets)
    if tweets:
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(tweet, "green"))
            elif score < 0.0:
                print(colored(tweet, "red"))
            else:
                print(colored(tweet, "yellow"))
    else:
        sys.exit("private user or some error")

if __name__ == "__main__":
    main()
